version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: jruby:9.3
    executor: ruby/default
    steps:
      - run: sudo apt-get update && sudo apt-get install -y git sudo tar
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check
      - run:
          name: Latex Install
          command: sudo apt-get install texlive-luatex && sudo apt-get install texlive
      - run:
          name: Run unit tests
          command: bundle exec rake
      - store_test_results:
          path: '.'

workflow:
  version: 2.1
  build-test:
    jobs:
      - build